// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/example/example_service.proto

package example

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_example_example_service_proto protoreflect.FileDescriptor

const file_api_example_example_service_proto_rawDesc = "" +
	"\n" +
	"!api/example/example_service.proto\x12\aexample\x1a\x1aapi/example/messages.proto2\x98\x01\n" +
	"\aExample\x12G\n" +
	"\n" +
	"CreatePost\x12\x1a.example.CreatePostRequest\x1a\x1b.example.CreatePostResponse\"\x00\x12D\n" +
	"\tListPosts\x12\x19.example.ListPostsRequest\x1a\x1a.example.ListPostsResponse\"\x00B\x8a\x01\n" +
	"\vcom.exampleB\x13ExampleServiceProtoP\x01Z*github.com/zholdaskali/go_grpc/pkg/example\xa2\x02\x03EXX\xaa\x02\aExample\xca\x02\aExample\xe2\x02\x13Example\\GPBMetadata\xea\x02\aExampleb\x06proto3"

var file_api_example_example_service_proto_goTypes = []any{
	(*CreatePostRequest)(nil),  // 0: example.CreatePostRequest
	(*ListPostsRequest)(nil),   // 1: example.ListPostsRequest
	(*CreatePostResponse)(nil), // 2: example.CreatePostResponse
	(*ListPostsResponse)(nil),  // 3: example.ListPostsResponse
}
var file_api_example_example_service_proto_depIdxs = []int32{
	0, // 0: example.Example.CreatePost:input_type -> example.CreatePostRequest
	1, // 1: example.Example.ListPosts:input_type -> example.ListPostsRequest
	2, // 2: example.Example.CreatePost:output_type -> example.CreatePostResponse
	3, // 3: example.Example.ListPosts:output_type -> example.ListPostsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_example_example_service_proto_init() }
func file_api_example_example_service_proto_init() {
	if File_api_example_example_service_proto != nil {
		return
	}
	file_api_example_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_example_example_service_proto_rawDesc), len(file_api_example_example_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_example_example_service_proto_goTypes,
		DependencyIndexes: file_api_example_example_service_proto_depIdxs,
	}.Build()
	File_api_example_example_service_proto = out.File
	file_api_example_example_service_proto_goTypes = nil
	file_api_example_example_service_proto_depIdxs = nil
}
